import { Inter } from 'next/font/google'
import './globals.css'
import { ConfigProvider } from 'antd'
import zhCN from 'antd/locale/zh_CN'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (
    <html lang="zh-CN">
      <body className={inter.className}>
        <ConfigProvider
          locale={zhCN}
          theme={{
            components: {
              ColorPicker: {
                popupOverlayInnerPadding: 8,
              },
              Select: {
                zIndexPopup: 1100,
              },
            },
            token: {
              colorPrimary: '#2d3efa',
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
